"use client";
/**
 * Robots.txt editor (CMS SEO Operations design). A monospace editor for the site's robots.txt with live
 * line/byte counts, a lightweight validation summary, and Restore Default. Native POST to /api/cms/robots
 * stores the content (cms_setting scope='robots'). Responsive to 360px.
 */
import { useMemo, useState } from "react";
import type { ReactNode } from "react";
import { CheckCircle2, AlertTriangle, RotateCcw } from "lucide-react";

// Mirrors the site's real robots (apps/web/public/robots.txt): a Next.js marketing site, so it allows
// everything crawlable and points at the single real sitemap. Only the internal API routes are disallowed.
export const DEFAULT_ROBOTS = `# Robots.txt for https://nexoristech.com
# Generated by Nexoris CMS

User-agent: *
Allow: /

# Keep internal endpoints out of search
Disallow: /api/

# Sitemap
Sitemap: https://nexoristech.com/sitemap.xml`;

export function RobotsEditor({ initial, lastSaved }: { initial: string; lastSaved: string | null }): ReactNode {
  const [text, setText] = useState(initial || DEFAULT_ROBOTS);
  const stats = useMemo(() => {
    const lines = text.split("\n").length;
    const bytes = new TextEncoder().encode(text).length;
    const hasUserAgent = /^user-agent:/im.test(text);
    const hasSitemap = /^sitemap:/im.test(text);
    return { lines, bytes, hasUserAgent, hasSitemap };
  }, [text]);
  const issues = [
    { ok: stats.hasUserAgent, label: "Has a User-agent directive" },
    { ok: stats.hasSitemap, label: "References a sitemap" },
    { ok: stats.bytes < 500 * 1024, label: "Under the 500KB size limit" },
  ];
  const valid = issues.every((i) => i.ok);

  return (
    <form action="/api/cms/robots" method="post">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <p className="text-[0.78rem] text-slate-500">{lastSaved ? `Last saved ${new Date(lastSaved).toLocaleString("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" })}` : "Not saved yet"}</p>
        <div className="flex items-center gap-2">
          <button type="button" onClick={() => setText(DEFAULT_ROBOTS)} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3.5 py-2 text-[0.82rem] font-600 text-slate-700 hover:bg-slate-50"><RotateCcw size={14} /> Restore Default</button>
          <button type="submit" className="rounded-lg bg-[#543CDA] px-5 py-2 text-[0.82rem] font-600 text-white hover:bg-[#4330B8]">Save Changes</button>
        </div>
      </div>

      <input type="hidden" name="content" value={text} />
      <div className="mt-4 grid grid-cols-1 gap-4 lg:grid-cols-[1fr_280px]">
        <div className="overflow-hidden rounded-xl border border-slate-200 bg-[#0f172a]">
          <div className="flex items-center justify-between border-b border-white/10 px-4 py-2 text-[0.72rem] text-slate-500"><span>Active robots.txt</span><span>{stats.lines} lines · {stats.bytes} bytes</span></div>
          <textarea value={text} onChange={(e) => setText(e.target.value)} spellCheck={false} rows={20}
            className="w-full resize-none bg-transparent px-4 py-3 font-mono text-[0.8rem] leading-relaxed text-slate-100 focus:outline-none" />
        </div>

        <div className="flex flex-col gap-4">
          <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-subtle">
            <h3 className="flex items-center gap-1.5 text-[0.85rem] font-700 text-slate-900">Validation {valid ? <CheckCircle2 size={15} className="text-[#15803D]" /> : <AlertTriangle size={15} className="text-[#B45309]" />}</h3>
            <ul className="mt-3 space-y-2">
              {issues.map((i) => (
                <li key={i.label} className="flex items-center gap-2 text-[0.8rem]">
                  {i.ok ? <CheckCircle2 size={15} className="shrink-0 text-[#15803D]" /> : <AlertTriangle size={15} className="shrink-0 text-[#B45309]" />}
                  <span className={i.ok ? "text-slate-600" : "text-slate-500"}>{i.label}</span>
                </li>
              ))}
            </ul>
            <p className={`mt-3 rounded-lg px-3 py-2 text-[0.78rem] font-600 ${valid ? "bg-[#DCFCE7] text-[#15803D]" : "bg-[#FEF3C7] text-[#B45309]"}`}>{valid ? "No issues found" : "Review the items above"}</p>
          </section>
        </div>
      </div>
    </form>
  );
}
