/**
 * Rebuilding the website's sitemap on demand.
 *
 * The Sitemap Manager had a "Regenerate" button with no handler. The sitemap is generated by the
 * website from the published content, so regenerating it means asking that app to rebuild the route —
 * the same call a publish makes. This is that call, on demand, for when someone wants it now.
 */
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { getCmsStaffFor } from "../../../../lib/auth.js";
import { notifyPublished } from "../../../../lib/publish-notify.js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST(request: NextRequest): Promise<Response> {
  const back = new URL("/cms/seo/sitemap", request.url);

  // Rebuilding what search engines read is an SEO operation, not general CMS access.
  const staff = await getCmsStaffFor("seo.manage");
  if (!staff) {
    back.searchParams.set("denied", "1");
    return NextResponse.redirect(back, { status: 303 });
  }

  // The insight hub is passed as the path because notifyPublished always rebuilds /sitemap.xml and
  // /llms.txt alongside whatever it is given; those two are the point of this call.
  const result = await notifyPublished({ path: "/insights", kind: "insight", published: true });
  back.searchParams.set("regenerated", result.revalidated ? "1" : "0");
  return NextResponse.redirect(back, { status: 303 });
}
